sonar.host.url=http://localhost:9000
sonar.projectKey=steam_playtime
sonar.token=sqp_12cc91e76779ecf6be8afb55b3ce7ebd8570497f

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,.git/**
sonar.sourceEncoding=UTF-8


# Run met: sonar-scanner